"""google oauth user model

Revision ID: fed76146575f
Revises: 7c057f2ab43d
Create Date: 2025-12-08 14:40:28.952135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed76146575f'
down_revision = '7c057f2ab43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        # Give the unique constraint a name!
        batch_op.create_unique_constraint("uq_users_google_sub", ['google_sub'])


def downgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_google_sub", type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('google_sub')
